/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model(props) {
    const { nodes, materials } = useGLTF('/assets/models/bone_model.glb')
    return (
        <group {...props} dispose={null}>
            <mesh castShadow receiveShadow geometry={nodes.Node1.geometry} material={materials.x1}>
                <meshStandardMaterial color="#373227"/>
            </mesh>
        </group>
    )
}

export default Model

useGLTF.preload('/assets/models/bone_model.glb')